# ETL

### Cargar Librerias

In [1]:
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

### Cargar Datos

Datos extraidos de la página:  https://www.kaggle.com/wendykan/lending-club-loan-data

In [3]:
loan_data_backup = pd.read_csv('../1_Data/loan.csv')

In [4]:
loan_data = loan_data_backup.copy()  #Se realiza una copia de los datos para ser modificados

In [5]:
pd.options.display.max_columns = None
# Modificación de las opciones de pandas para mostrar todas las columnas del dataframe

In [6]:
loan_data.head(3)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,2500,2500,2500.0,36 months,13.56,84.92,C,C1,Chef,10+ years,RENT,55000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,109xx,NY,18.24,0.0,Apr-2001,1.0,NaN,45.0,9.0,1.0,4341,10.3,34.0,w,2386.02,2386.02,167.02,167.02,113.98,53.04,0.0,0.0,0.0,Feb-2019,84.92,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,16901.0,2.0,2.0,1.0,2.0,2.0,12560.0,69.0,2.0,7.0,2137.0,28.0,42000.0,1.0,11.0,2.0,9.0,1878.0,34360.0,5.9,0.0,0.0,140.0,212.0,1.0,1.0,0.0,1.0,NaN,2.0,NaN,0.0,2.0,5.0,3.0,3.0,16.0,7.0,18.0,5.0,9.0,0.0,0.0,0.0,3.0,100.0,0.0,1.0,0.0,60124.0,16901.0,36500.0,18124.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,30000,30000,30000.0,60 months,18.94,777.23,D,D2,Postmaster,10+ years,MORTGAGE,90000.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,713xx,LA,26.52,0.0,Jun-1987,0.0,71.0,75.0,13.0,1.0,12315,24.2,44.0,w,29387.75,29387.75,1507.11,1507.11,612.25,894.86,0.0,0.0,0.0,Feb-2019,777.23,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,1208.0,321915.0,4.0,4.0,2.0,3.0,3.0,87153.0,88.0,4.0,5.0,998.0,57.0,50800.0,2.0,15.0,2.0,10.0,24763.0,13761.0,8.3,0.0,0.0,163.0,378.0,4.0,3.0,3.0,4.0,NaN,4.0,NaN,0.0,2.0,4.0,4.0,9.0,27.0,8.0,14.0,4.0,13.0,0.0,0.0,0.0,6.0,95.0,0.0,1.0,0.0,372872.0,99468.0,15000.0,94072.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,5000,5000,5000.0,36 months,17.97,180.69,D,D1,Administrative,6 years,MORTGAGE,59280.0,Source Verified,Dec-2018,Current,n,NaN,NaN,debt_consolidation,Debt consolidation,490xx,MI,10.51,0.0,Apr-2011,0.0,NaN,NaN,8.0,0.0,4599,19.1,13.0,w,4787.21,4787.21,353.89,353.89,212.79,141.10,0.0,0.0,0.0,Feb-2019,180.69,Mar-2019,Feb-2019,0.0,NaN,1,Individual,NaN,NaN,NaN,0.0,0.0,110299.0,0.0,1.0,0.0,2.0,14.0,7150.0,72.0,0.0,2.0,0.0,35.0,24100.0,1.0,5.0,0.0,4.0,18383.0,13800.0,0.0,0.0,0.0,87.0,92.0,15.0,14.0,2.0,77.0,NaN,14.0,NaN,0.0,0.0,3.0,3.0,3.0,4.0,6.0,7.0,3.0,8.0,0.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,136927.0,11749.0,13800.0,10000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
loan_data.shape

(2260668, 145)

145 variables y 2.260.668 muestras (filas)

### Transformación de Datos

In [8]:
# Verificación de campos
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'acc_open_past_24mths',
       'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_bc_dlq',
       'mths_since_recent_inq', 'mths_since_recent_revol_delinq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'revol_bal_joint',
       'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths',
       'sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag',
       'hardship_type', 'hardship_reason', 'hardship_status',
       'deferral_term', 'hardship_amount', 'hardship_start_date',
       'hardship_end_date', 'payment_plan_start_date', 'hardship_length',
       'hardship_dpd', 'hardship_loan_status',
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status',
       'settlement_date', 'settlement_amount', 'settlement_percentage',
       'settlement_term'], dtype=object)

Se deberían entender las 145 variables que contiene la base de datos, para lo cual se requiere un experto en el dominio de conocimiento.  Para el siguiene análisis se dividirán en varaibles continuas y discretas.  Para el análisis de riesgo y con el fin de que los modelos puedan ser explicativos, se transformaran a variables discretas tipo dummy

### Principales variables a usar

#### Variables 'continuas'
- emp_lenght se transforma a emp_lenght_int: años de experiencia laboral.  Variable categoria que se transformará a números para ser input de los modelos
- earliest_cr_line se transforma a earliest_cr_line_date y finalmente a mths_since_earliest_cr_line: Fecha de la primera linea de crédito se transforma luego a meses desde esa primera linea de crédito hasta la fecha de dic 2017 (suponiendo que el analisi sse hace en dicha fecha)
- term: duración en meses del crédito
- issue_d se transforma a issue_d_date y luego a mths_since_issue_d: Se transforma de fecha a meses hasta una fecha de corte

#### Variables 'Discretas'
se crean varaibles dummy de las variables:

grade, sub_grade, home_ownership, verification_status, loan_status, purpose, addr_state, initial_list_status

### Transformación de Algunas Variables Continuas

In [9]:
loan_data['emp_length'].unique()
# Displays unique values of a column.

array(['10+ years', '6 years', '4 years', '< 1 year', '2 years',
       '9 years', nan, '5 years', '3 years', '7 years', '1 year',
       '8 years'], dtype=object)

In [19]:
#Se usa str.replace para dejar solo los numeros (aún como strings).  \ es un caracter de escape
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('nan',  str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

In [20]:
loan_data['emp_length_int'].unique()

array(['10', '6', '4', '0', '2', '9', nan, '5', '3', '7', '1', '8'],
      dtype=object)

In [27]:
type(loan_data['emp_length_int'][0]) #verificar el tipo de datos => sabemos que es string

str

In [28]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])  #transformar de str a num
print(type(loan_data['emp_length_int'][0]))

<class 'numpy.float64'>

In [29]:
loan_data['earliest_cr_line'][0:5]

0    Apr-2001
1    Jun-1987
2    Apr-2011
3    Feb-2006
4    Dec-2000
Name: earliest_cr_line, dtype: object

In [38]:
type(loan_data['earliest_cr_line'][0])

str

In [30]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'])
print(type(loan_data['earliest_cr_line_date'][0]))
# Se transforma de tipo objeto a fecha con formato estandar de pandas

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [40]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [41]:
loan_data['earliest_cr_line_date'].describe()

count                 2260639
unique                    754
top       2004-09-01 00:00:00
freq                    15400
first     1933-03-01 00:00:00
last      2015-11-01 00:00:00
Name: earliest_cr_line_date, dtype: object

Para el modelo de crédito es más util el calculo de dias, meses o periodos entre fechas que el dato de la fecha, se calculará entonces los días entre la fecha y la fecha final del dataset (o fecha de uso del dataset)

In [32]:
# Asumiendo que estamos en dic de 2017
#Se realiza una resta entre fechas y las respuesta es en días.  estos dias se pasan a numeros y luego
#se usa función de numpy para transformar los días a meses.  Finalmente se redondea a entero
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') -
                                                                loan_data['earliest_cr_line_date']) /
                                                               np.timedelta64(1, 'M')))

In [33]:
loan_data['mths_since_earliest_cr_line'][0:5]

0    200.0
1    366.0
2     80.0
3    142.0
4    204.0
Name: mths_since_earliest_cr_line, dtype: float64

In [34]:
loan_data['mths_since_earliest_cr_line'].describe()

count    2.260639e+06
mean     2.156891e+02
std      9.416722e+01
min      2.500000e+01
25%      1.510000e+02
50%      2.000000e+02
75%      2.650000e+02
max      1.017000e+03
Name: mths_since_earliest_cr_line, dtype: float64

In [43]:
loan_data['term'][0:5]

0     36 months
1     60 months
2     36 months
3     36 months
4     60 months
Name: term, dtype: object

In [44]:
loan_data['term'].describe()

count        2260668
unique             2
top        36 months
freq         1609754
Name: term, dtype: object

In [45]:
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace(' months', ''))
type(loan_data['term_int'][0])

numpy.int64

In [46]:
loan_data['issue_d'][0:3]

0    Dec-2018
1    Dec-2018
2    Dec-2018
Name: issue_d, dtype: object

In [47]:
# Asumiendo que estamos en dic 2017
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'])
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'M')))
loan_data['mths_since_issue_d'].describe()

count    2.260668e+06
mean     1.895439e+01
std      2.161178e+01
min     -1.200000e+01
25%      1.000000e+00
50%      1.700000e+01
75%      3.200000e+01
max      1.260000e+02
Name: mths_since_issue_d, dtype: float64

### Transformación de Algunas Variables Discretas

In [49]:
loan_data['grade'].unique()

array(['C', 'D', 'B', 'A', 'E', 'F', 'G'], dtype=object)

In [56]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]
# Se crean varaibles dummy con las 8 varaibles originales y se coloca un prefijo para no perder el nombre de la variable
# Note that we are using a particular naming convention for all variables: original variable name, colon, category name.
#los datos se guardan en una lista de python

In [59]:
type(loan_data_dummies)

list

In [60]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)
#se transforma la lista en un data frame
print(loan_data_dummies.head())
print(loan_data_dummies.shape)

   grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G  \
0        0        0        1        0        0        0        0
1        0        0        0        1        0        0        0
2        0        0        0        1        0        0        0
3        0        0        0        1        0        0        0
4        0        0        1        0        0        0        0

   sub_grade:A1  sub_grade:A2  sub_grade:A3  sub_grade:A4  sub_grade:A5  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   sub_grade:B1  sub_grade:B2  sub_grade:B3  sub_grade:B4  sub_grade:B5  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   sub_grade:C1  sub_grade:C2  sub_grade:C3  sub_grade:C4  sub_grade:C5  \
0             1             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             1             0

   sub_grade:D1  sub_grade:D2  sub_grade:D3  sub_grade:D4  sub_grade:D5  \
0             0             0             0             0             0
1             0             1             0             0             0
2             1             0             0             0             0
3             0             1             0             0             0
4             0             0             0             0             0

   sub_grade:E1  sub_grade:E2  sub_grade:E3  sub_grade:E4  sub_grade:E5  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   sub_grade:F1  sub_grade:F2  sub_grade:F3  sub_grade:F4  sub_grade:F5  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   sub_grade:G1  sub_grade:G2  sub_grade:G3  sub_grade:G4  sub_grade:G5  \
0             0             0             0             0             0
1             0             0             0             0             0
2             0             0             0             0             0
3             0             0             0             0             0
4             0             0             0             0             0

   home_ownership:ANY  home_ownership:MORTGAGE  home_ownership:NONE  \
0                   0                        0                    0
1                   0                        1                    0
2                   0                        1                    0
3                   0                        1                    0
4                   0                        1                    0

   home_ownership:OTHER  home_ownership:OWN  home_ownership:RENT  \
0                     0                   0                    1
1                     0                   0                    0
2                     0                   0                    0
3                     0                   0                    0
4                     0                   0                    0

   verification_status:Not Verified  verification_status:Source Verified  \
0                                 1                                    0
1                                 0                                    1
2                                 0                                    1
3                                 0                                    1
4                                 1                                    0

   verification_status:Verified  loan_status:Charged Off  loan_status:Current  \
0                             0                        0                    1
1                             0                        0                    1
2                             0                        0                    1
3                             0                        0                    1
4                             0                        0                    1

   loan_status:Default  \
0                    0
1                    0
2                    0
3                    0
4                    0

   loan_status:Does not meet the credit policy. Status:Charged Off  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   loan_status:Does not meet the credit policy. Status:Fully Paid  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   loan_status:Fully Paid  loan_status:In Grace Period  \
0                       0                            0
1                       0                            0
2                       0                            0
3                       0                            0
4                       0                            0

   loan_status:Late (16-30 days)  loan_status:Late (31-120 days)  purpose:car  \
0                              0                               0            0
1                              0                               0            0
2                              0                               0            0
3                              0                               0            0
4                              0                               0            0

   purpose:credit_card  purpose:debt_consolidation  purpose:educational  \
0                    0                           1                    0
1                    0                           1                    0
2                    0                           1                    0
3                    0                           1                    0
4                    0                           1                    0

   purpose:home_improvement  purpose:house  purpose:major_purchase  \
0                         0              0                       0
1                         0              0                       0
2                         0              0                       0
3                         0              0                       0
4                         0              0                       0

   purpose:medical  purpose:moving  purpose:other  purpose:renewable_energy  \
0                0               0              0                         0
1                0               0              0                         0
2                0               0              0                         0
3                0               0              0                         0
4                0               0              0                         0

   purpose:small_business  purpose:vacation  purpose:wedding  addr_state:AK  \
0                       0                 0                0              0
1                       0                 0                0              0
2                       0                 0                0              0
3                       0                 0                0              0
4                       0                 0                0              0

   addr_state:AL  addr_state:AR  addr_state:AZ  addr_state:CA  addr_state:CO  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:CT  addr_state:DC  addr_state:DE  addr_state:FL  addr_state:GA  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:HI  addr_state:IA  addr_state:ID  addr_state:IL  addr_state:IN  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:KS  addr_state:KY  addr_state:LA  addr_state:MA  addr_state:MD  \
0              0              0              0              0              0
1              0              0              1              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              1

   addr_state:ME  addr_state:MI  addr_state:MN  addr_state:MO  addr_state:MS  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              1              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:MT  addr_state:NC  addr_state:ND  addr_state:NE  addr_state:NH  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:NJ  addr_state:NM  addr_state:NV  addr_state:NY  addr_state:OH  \
0              0              0              0              1              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:OK  addr_state:OR  addr_state:PA  addr_state:RI  addr_state:SC  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:SD  addr_state:TN  addr_state:TX  addr_state:UT  addr_state:VA  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              0              0              0              0
4              0              0              0              0              0

   addr_state:VT  addr_state:WA  addr_state:WI  addr_state:WV  addr_state:WY  \
0              0              0              0              0              0
1              0              0              0              0              0
2              0              0              0              0              0
3              0              1              0              0              0
4              0              0              0              0              0

   initial_list_status:f  initial_list_status:w
0                      0                      1
1                      0                      1
2                      0                      1
3                      0                      1
4                      0                      1
(2260668, 127)

Las 8 variables categoricas originales se transformaron en 127 varibles tipo Dummy.  Se debe tener en cuenta que no se ha eliminado una de ellas en cada dummy lo cual se debe hacer en la modelación

In [61]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)
#las nueva variables se adicionan al dataframe original

### Se depuran los datos vacios

In [63]:
pd.options.display.max_rows = None
# Opción para que Panda mueste todas las filas de los dataframes
loan_data.isnull().sum()
#Verificar si existen valores nulos para cada variable

id                                                                 2260668
member_id                                                          2260668
loan_amnt                                                                0
funded_amnt                                                              0
funded_amnt_inv                                                          0
term                                                                     0
int_rate                                                                 0
installment                                                              0
grade                                                                    0
sub_grade                                                                0
emp_title                                                           166969
emp_length                                                          146907
home_ownership                                                           0
annual_inc                                                               4
verification_status                                                      0
issue_d                                                                  0
loan_status                                                              0
pymnt_plan                                                               0
url                                                                2260668
desc                                                               2134601
purpose                                                                  0
title                                                                23325
zip_code                                                                 1
addr_state                                                               0
dti                                                                   1711
delinq_2yrs                                                             29
earliest_cr_line                                                        29
inq_last_6mths                                                          30
mths_since_last_delinq                                             1158502
mths_since_last_record                                             1901512
open_acc                                                                29
pub_rec                                                                 29
revol_bal                                                                0
revol_util                                                            1802
total_acc                                                               29
initial_list_status                                                      0
out_prncp                                                                0
out_prncp_inv                                                            0
total_pymnt                                                              0
total_pymnt_inv                                                          0
total_rec_prncp                                                          0
total_rec_int                                                            0
total_rec_late_fee                                                       0
recoveries                                                               0
collection_recovery_fee                                                  0
last_pymnt_d                                                          2426
last_pymnt_amnt                                                          0
next_pymnt_d                                                       1303607
last_credit_pull_d                                                      73
collections_12_mths_ex_med                                             145
mths_since_last_major_derog                                        1679893
policy_code                                                              0
application_type                                                         0
annual_inc_joint                                                   2139958
dti_joint                                                          2139962
verification_status_joint                                          2144938
acc_now_delinq                                                          29
tot_coll_amt                                                         70276
tot_cur_bal                                                          70276
open_acc_6m                                                         866130
open_act_il                                                         866129
open_il_12m                                                         866129
open_il_24m                                                         866129
mths_since_rcnt_il                                                  909924
total_bal_il                                                        866129
il_util                                                            1068850
open_rv_12m                                                         866129
open_rv_24m                                                         866129
max_bal_bc                                                          866129
all_util                                                            866348
total_rev_hi_lim                                                     70276
inq_fi                                                              866129
total_cu_tl                                                         866130
inq_last_12m                                                        866130
acc_open_past_24mths                                                 50030
avg_cur_bal                                                          70346
bc_open_to_buy                                                       74935
bc_util                                                              76071
chargeoff_within_12_mths                                               145
delinq_amnt                                                             29
mo_sin_old_il_acct                                                  139071
mo_sin_old_rev_tl_op                                                 70277
mo_sin_rcnt_rev_tl_op                                                70277
mo_sin_rcnt_tl                                                       70276
mort_acc                                                             50030
mths_since_recent_bc                                                 73412
mths_since_recent_bc_dlq                                           1740967
mths_since_recent_inq                                               295435
mths_since_recent_revol_delinq                                     1520309
num_accts_ever_120_pd                                                70276
num_actv_bc_tl                                                       70276
num_actv_rev_tl                                                      70276
num_bc_sats                                                          58590
num_bc_tl                                                            70276
num_il_tl                                                            70276
num_op_rev_tl                                                        70276
num_rev_accts                                                        70277
num_rev_tl_bal_gt_0                                                  70276
num_sats                                                             58590
num_tl_120dpd_2m                                                    153657
num_tl_30dpd                                                         70276
num_tl_90g_dpd_24m                                                   70276
num_tl_op_past_12m                                                   70276
pct_tl_nvr_dlq                                                       70431
percent_bc_gt_75                                                     75379
pub_rec_bankruptcies                                                  1365
tax_liens                                                              105
tot_hi_cred_lim                                                      70276
total_bal_ex_mort                                                    50030
total_bc_limit                                                       50030
total_il_high_credit_limit                                           70276
revol_bal_joint                                                    2152648
sec_app_earliest_cr_line                                           2152647
sec_app_inq_last_6mths                                             2152647
sec_app_mort_acc                                                   2152647
sec_app_open_acc                                                   2152647
sec_app_revol_util                                                 2154484
sec_app_open_act_il                                                2152647
sec_app_num_rev_accts                                              2152647
sec_app_chargeoff_within_12_mths                                   2152647
sec_app_collections_12_mths_ex_med                                 2152647
sec_app_mths_since_last_major_derog                                2224726
hardship_flag                                                            0
hardship_type                                                      2250055
hardship_reason                                                    2250055
hardship_status                                                    2250055
deferral_term                                                      2250055
hardship_amount                                                    2250055
hardship_start_date                                                2250055
hardship_end_date                                                  2250055
payment_plan_start_date                                            2250055
hardship_length                                                    2250055
hardship_dpd                                                       2250055
hardship_loan_status                                               2250055
orig_projected_additional_accrued_interest                         2252242
hardship_payoff_balance_amount                                     2250055
hardship_last_payment_amount                                       2250055
disbursement_method                                                      0
debt_settlement_flag                                                     0
debt_settlement_flag_date                                          2227612
settlement_status                                                  2227612
settlement_date                                                    2227612
settlement_amount                                                  2227612
settlement_percentage                                              2227612
settlement_term                                                    2227612
emp_length_int                                                      146907
earliest_cr_line_date                                                   29
mths_since_earliest_cr_line                                             29
term_int                                                                 0
issue_d_date                                                             0
mths_since_issue_d                                                       0
grade:A                                                                  0
grade:B                                                                  0
grade:C                                                                  0
grade:D                                                                  0
grade:E                                                                  0
grade:F                                                                  0
grade:G                                                                  0
sub_grade:A1                                                             0
sub_grade:A2                                                             0
sub_grade:A3                                                             0
sub_grade:A4                                                             0
sub_grade:A5                                                             0
sub_grade:B1                                                             0
sub_grade:B2                                                             0
sub_grade:B3                                                             0
sub_grade:B4                                                             0
sub_grade:B5                                                             0
sub_grade:C1                                                             0
sub_grade:C2                                                             0
sub_grade:C3                                                             0
sub_grade:C4                                                             0
sub_grade:C5                                                             0
sub_grade:D1                                                             0
sub_grade:D2                                                             0
sub_grade:D3                                                             0
sub_grade:D4                                                             0
sub_grade:D5                                                             0
sub_grade:E1                                                             0
sub_grade:E2                                                             0
sub_grade:E3                                                             0
sub_grade:E4                                                             0
sub_grade:E5                                                             0
sub_grade:F1                                                             0
sub_grade:F2                                                             0
sub_grade:F3                                                             0
sub_grade:F4                                                             0
sub_grade:F5                                                             0
sub_grade:G1                                                             0
sub_grade:G2                                                             0
sub_grade:G3                                                             0
sub_grade:G4                                                             0
sub_grade:G5                                                             0
home_ownership:ANY                                                       0
home_ownership:MORTGAGE                                                  0
home_ownership:NONE                                                      0
home_ownership:OTHER                                                     0
home_ownership:OWN                                                       0
home_ownership:RENT                                                      0
verification_status:Not Verified                                         0
verification_status:Source Verified                                      0
verification_status:Verified                                             0
loan_status:Charged Off                                                  0
loan_status:Current                                                      0
loan_status:Default                                                      0
loan_status:Does not meet the credit policy. Status:Charged Off          0
loan_status:Does not meet the credit policy. Status:Fully Paid           0
loan_status:Fully Paid                                                   0
loan_status:In Grace Period                                              0
loan_status:Late (16-30 days)                                            0
loan_status:Late (31-120 days)                                           0
purpose:car                                                              0
purpose:credit_card                                                      0
purpose:debt_consolidation                                               0
purpose:educational                                                      0
purpose:home_improvement                                                 0
purpose:house                                                            0
purpose:major_purchase                                                   0
purpose:medical                                                          0
purpose:moving                                                           0
purpose:other                                                            0
purpose:renewable_energy                                                 0
purpose:small_business                                                   0
purpose:vacation                                                         0
purpose:wedding                                                          0
addr_state:AK                                                            0
addr_state:AL                                                            0
addr_state:AR                                                            0
addr_state:AZ                                                            0
addr_state:CA                                                            0
addr_state:CO                                                            0
addr_state:CT                                                            0
addr_state:DC                                                            0
addr_state:DE                                                            0
addr_state:FL                                                            0
addr_state:GA                                                            0
addr_state:HI                                                            0
addr_state:IA                                                            0
addr_state:ID                                                            0
addr_state:IL                                                            0
addr_state:IN                                                            0
addr_state:KS                                                            0
addr_state:KY                                                            0
addr_state:LA                                                            0
addr_state:MA                                                            0
addr_state:MD                                                            0
addr_state:ME                                                            0
addr_state:MI                                                            0
addr_state:MN                                                            0
addr_state:MO                                                            0
addr_state:MS                                                            0
addr_state:MT                                                            0
addr_state:NC                                                            0
addr_state:ND                                                            0
addr_state:NE                                                            0
addr_state:NH                                                            0
addr_state:NJ                                                            0
addr_state:NM                                                            0
addr_state:NV                                                            0
addr_state:NY                                                            0
addr_state:OH                                                            0
addr_state:OK                                                            0
addr_state:OR                                                            0
addr_state:PA                                                            0
addr_state:RI                                                            0
addr_state:SC                                                            0

In [64]:
pd.options.display.max_rows = 100
# Solo mostrar 10 filas

In [66]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace=True)
# se llenan los datos vacios de total_rev_hi_lim con los datos de funded_amnt para la misma fila

In [68]:
loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)
#los datos vacios de annual_inc se llenan con la media

In [69]:
loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True)
loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)
# Se llenan los datos vacios con cero

### Preparación de la Variable Dependiente

In [71]:
loan_data['loan_status'].unique()

array(['Current', 'Fully Paid', 'Late (31-120 days)', 'In Grace Period',
       'Charged Off', 'Late (16-30 days)', 'Default',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

In [72]:
loan_data['loan_status'].value_counts()

Fully Paid                                             1041952
Current                                                 919695
Charged Off                                             261655
Late (31-120 days)                                       21897
In Grace Period                                           8952
Late (16-30 days)                                         3737
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     31
Name: loan_status, dtype: int64

In [73]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()

Fully Paid                                             0.460904
Current                                                0.406824
Charged Off                                            0.115742
Late (31-120 days)                                     0.009686
In Grace Period                                        0.003960
Late (16-30 days)                                      0.001653
Does not meet the credit policy. Status:Fully Paid     0.000879
Does not meet the credit policy. Status:Charged Off    0.000337
Default                                                0.000014
Name: loan_status, dtype: float64

In [74]:
# Se transforma a una varaible binaria - good - bad
#las categorias 'Charged Off', 'Default','Does not meet the credit policy. Status:Charged Off', 'Late (31-120 days)'
#Se consideran Bad=0, las demás o estan al día o están pagadas se condireran good=1
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                       'Does not meet the credit policy. Status:Charged Off',
                                                       'Late (31-120 days)']), 0, 1)

In [76]:
loan_data['good_bad'].unique()

array([1, 0], dtype=int64)